# Generated by Django 3.2 on 2021-04-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='date_time',
            field=models.CharField(max_length=500),
        ),
    ]
