# Generated by Django 3.2 on 2021-04-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_historymodel_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
